server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backendprojectdb
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #create #update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  profiles:
    include:
      - open   #application-open.yml
      - oauth2 #application-oauth2.yml

  # 기본설정
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  # JSON 직렬화 설정
  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    allow-bean-definition-overriding: true



#로그 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
